spring: 
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/airlines
        username: root
        password: 38326042zla
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 0
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
dollar:
    url: ${DOLLAR_URL:https://dolarapi.com/v1/dolares/tarjeta}
