server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/Daniela38/flights-microservices.git
                    search-paths: config-data
    application:
        name: config-service
